name: isolate_handler_example
description: Demonstrates how to use the isolate_handler plugin.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  isolate_handler:
    path: ../

  path_provider: ^1.6.9
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
