name: isolate_handler
description: Effortless isolates abstraction layer with support for inter-isolate communication.
version: 0.3.0
homepage: https://github.com/deakjahn/isolate_handler
documentation: https://github.com/deakjahn/isolate_handler/blob/0.2.0/README.md

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_isolate: ^1.0.0+13

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
